networks:
  trustvault:
    driver: bridge

services:
  backend:
    build: ./backend
    container_name: trustvault-backend
    ports:
      - "8080:8080"
    environment:
      - DYNAMODB_ENDPOINT=http://dynamodb:8000
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/app:/app/app
    depends_on:
      - dynamodb
    networks:
      - trustvault

  dynamodb:
    image: amazon/dynamodb-local:2.5.2
    container_name: trustvault-dynamodb
    command: -jar DynamoDBLocal.jar -sharedDb -inMemory
    ports:
      - "8000:8000"
    networks:
      - trustvault
    environment:
      - AWS_REGION=us-east-1

  dynamodb-admin:
    image: aaronshaf/dynamodb-admin:latest
    container_name: trustvault-dynamodb-admin
    ports:
      - "8001:8001"
    networks:
      - trustvault
    environment:
      - DYNAMO_ENDPOINT=http://dynamodb:8000
      - AWS_REGION=us-east-1
    depends_on:
      - dynamodb

# Frontend: Run locally for better dev experience
# Instructions: cd frontend && npm install && npm start
