version: '3.9'

services:
  backend:
    build: ./backend
    container_name: trustvault-backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
      - /app/.venv  # Don't overwrite venv
    env_file:
      - ./backend/.env
    environment:
      - PYTHONPATH=/app
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: trustvault-frontend
    ports:
      - "8081:8081"
    volumes:
      - ./frontend:/app
      - /app/node_modules  # Don't overwrite node_modules
    depends_on:
      - backend
    restart: unless-stopped
    stdin_open: true
    tty: true
